import { Survey } from "../survey/Survey";

export type AlcoholConsumptionSurvey = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  q1: string | null;
  q2: string | null;
  q3: string | null;
  q4: string | null;
  q5: string | null;
  q6: string | null;
  q7: string | null;
  q8: string | null;
  q9: string | null;
  q10: string | null;
  q11: string | null;
  q12: string | null;
  q13: string | null;
  q14: string | null;
  q15: string | null;
  q16: string | null;
  q17: string | null;
  q18: string | null;
  q19: string | null;
  q20: string | null;
  q21: string | null;
  q22: string | null;
  q23: string | null;
  q24: string | null;
  q25: string | null;
  survey?: Survey | null;
};
