/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OutletSurveyService } from "../outletSurvey.service";
import { OutletSurveyCreateInput } from "./OutletSurveyCreateInput";
import { OutletSurvey } from "./OutletSurvey";
import { OutletSurveyFindManyArgs } from "./OutletSurveyFindManyArgs";
import { OutletSurveyWhereUniqueInput } from "./OutletSurveyWhereUniqueInput";
import { OutletSurveyUpdateInput } from "./OutletSurveyUpdateInput";

export class OutletSurveyControllerBase {
  constructor(protected readonly service: OutletSurveyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OutletSurvey })
  async createOutletSurvey(
    @common.Body() data: OutletSurveyCreateInput
  ): Promise<OutletSurvey> {
    return await this.service.createOutletSurvey({
      data: {
        ...data,

        survey: data.survey
          ? {
              connect: data.survey,
            }
          : undefined,

        outlet: data.outlet
          ? {
              connect: data.outlet,
            }
          : undefined,

        policeStation: data.policeStation
          ? {
              connect: data.policeStation,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        q1: true,
        q2: true,
        q3: true,
        q4: true,
        q5: true,
        q6: true,
        q7: true,
        q8: true,
        q9: true,
        q10: true,
        q11: true,
        q12: true,

        survey: {
          select: {
            id: true,
          },
        },

        outlet: {
          select: {
            id: true,
          },
        },

        yesCount: true,
        noCount: true,

        policeStation: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [OutletSurvey] })
  @ApiNestedQuery(OutletSurveyFindManyArgs)
  async outletSurveys(@common.Req() request: Request): Promise<OutletSurvey[]> {
    const args = plainToClass(OutletSurveyFindManyArgs, request.query);
    return this.service.outletSurveys({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        q1: true,
        q2: true,
        q3: true,
        q4: true,
        q5: true,
        q6: true,
        q7: true,
        q8: true,
        q9: true,
        q10: true,
        q11: true,
        q12: true,

        survey: {
          select: {
            id: true,
          },
        },

        outlet: {
          select: {
            id: true,
          },
        },

        yesCount: true,
        noCount: true,

        policeStation: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OutletSurvey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async outletSurvey(
    @common.Param() params: OutletSurveyWhereUniqueInput
  ): Promise<OutletSurvey | null> {
    const result = await this.service.outletSurvey({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        q1: true,
        q2: true,
        q3: true,
        q4: true,
        q5: true,
        q6: true,
        q7: true,
        q8: true,
        q9: true,
        q10: true,
        q11: true,
        q12: true,

        survey: {
          select: {
            id: true,
          },
        },

        outlet: {
          select: {
            id: true,
          },
        },

        yesCount: true,
        noCount: true,

        policeStation: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OutletSurvey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOutletSurvey(
    @common.Param() params: OutletSurveyWhereUniqueInput,
    @common.Body() data: OutletSurveyUpdateInput
  ): Promise<OutletSurvey | null> {
    try {
      return await this.service.updateOutletSurvey({
        where: params,
        data: {
          ...data,

          survey: data.survey
            ? {
                connect: data.survey,
              }
            : undefined,

          outlet: data.outlet
            ? {
                connect: data.outlet,
              }
            : undefined,

          policeStation: data.policeStation
            ? {
                connect: data.policeStation,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          q1: true,
          q2: true,
          q3: true,
          q4: true,
          q5: true,
          q6: true,
          q7: true,
          q8: true,
          q9: true,
          q10: true,
          q11: true,
          q12: true,

          survey: {
            select: {
              id: true,
            },
          },

          outlet: {
            select: {
              id: true,
            },
          },

          yesCount: true,
          noCount: true,

          policeStation: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OutletSurvey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOutletSurvey(
    @common.Param() params: OutletSurveyWhereUniqueInput
  ): Promise<OutletSurvey | null> {
    try {
      return await this.service.deleteOutletSurvey({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          q1: true,
          q2: true,
          q3: true,
          q4: true,
          q5: true,
          q6: true,
          q7: true,
          q8: true,
          q9: true,
          q10: true,
          q11: true,
          q12: true,

          survey: {
            select: {
              id: true,
            },
          },

          outlet: {
            select: {
              id: true,
            },
          },

          yesCount: true,
          noCount: true,

          policeStation: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
