/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProvinceService } from "../province.service";
import { ProvinceCreateInput } from "./ProvinceCreateInput";
import { Province } from "./Province";
import { ProvinceFindManyArgs } from "./ProvinceFindManyArgs";
import { ProvinceWhereUniqueInput } from "./ProvinceWhereUniqueInput";
import { ProvinceUpdateInput } from "./ProvinceUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { OutletFindManyArgs } from "../../outlet/base/OutletFindManyArgs";
import { Outlet } from "../../outlet/base/Outlet";
import { OutletWhereUniqueInput } from "../../outlet/base/OutletWhereUniqueInput";
import { PoliceStationFindManyArgs } from "../../policeStation/base/PoliceStationFindManyArgs";
import { PoliceStation } from "../../policeStation/base/PoliceStation";
import { PoliceStationWhereUniqueInput } from "../../policeStation/base/PoliceStationWhereUniqueInput";

export class ProvinceControllerBase {
  constructor(protected readonly service: ProvinceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Province })
  async createProvince(
    @common.Body() data: ProvinceCreateInput
  ): Promise<Province> {
    return await this.service.createProvince({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Province] })
  @ApiNestedQuery(ProvinceFindManyArgs)
  async provinces(@common.Req() request: Request): Promise<Province[]> {
    const args = plainToClass(ProvinceFindManyArgs, request.query);
    return this.service.provinces({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Province })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async province(
    @common.Param() params: ProvinceWhereUniqueInput
  ): Promise<Province | null> {
    const result = await this.service.province({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Province })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProvince(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() data: ProvinceUpdateInput
  ): Promise<Province | null> {
    try {
      return await this.service.updateProvince({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Province })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProvince(
    @common.Param() params: ProvinceWhereUniqueInput
  ): Promise<Province | null> {
    try {
      return await this.service.deleteProvince({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: ProvinceWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        email: true,
        roles: true,

        province: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateProvince({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateProvince({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateProvince({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/outlets")
  @ApiNestedQuery(OutletFindManyArgs)
  async findOutlets(
    @common.Req() request: Request,
    @common.Param() params: ProvinceWhereUniqueInput
  ): Promise<Outlet[]> {
    const query = plainToClass(OutletFindManyArgs, request.query);
    const results = await this.service.findOutlets(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        address: true,

        province: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/outlets")
  async connectOutlets(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() body: OutletWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      outlets: {
        connect: body,
      },
    };
    await this.service.updateProvince({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/outlets")
  async updateOutlets(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() body: OutletWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      outlets: {
        set: body,
      },
    };
    await this.service.updateProvince({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/outlets")
  async disconnectOutlets(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() body: OutletWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      outlets: {
        disconnect: body,
      },
    };
    await this.service.updateProvince({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/policeStations")
  @ApiNestedQuery(PoliceStationFindManyArgs)
  async findPoliceStations(
    @common.Req() request: Request,
    @common.Param() params: ProvinceWhereUniqueInput
  ): Promise<PoliceStation[]> {
    const query = plainToClass(PoliceStationFindManyArgs, request.query);
    const results = await this.service.findPoliceStations(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        address: true,

        province: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/policeStations")
  async connectPoliceStations(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() body: PoliceStationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      policeStations: {
        connect: body,
      },
    };
    await this.service.updateProvince({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/policeStations")
  async updatePoliceStations(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() body: PoliceStationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      policeStations: {
        set: body,
      },
    };
    await this.service.updateProvince({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/policeStations")
  async disconnectPoliceStations(
    @common.Param() params: ProvinceWhereUniqueInput,
    @common.Body() body: PoliceStationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      policeStations: {
        disconnect: body,
      },
    };
    await this.service.updateProvince({
      where: params,
      data,
      select: { id: true },
    });
  }
}
