/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Survey } from "./Survey";
import { SurveyCountArgs } from "./SurveyCountArgs";
import { SurveyFindManyArgs } from "./SurveyFindManyArgs";
import { SurveyFindUniqueArgs } from "./SurveyFindUniqueArgs";
import { CreateSurveyArgs } from "./CreateSurveyArgs";
import { UpdateSurveyArgs } from "./UpdateSurveyArgs";
import { DeleteSurveyArgs } from "./DeleteSurveyArgs";
import { AlcoholConsumptionSurveyFindManyArgs } from "../../alcoholConsumptionSurvey/base/AlcoholConsumptionSurveyFindManyArgs";
import { AlcoholConsumptionSurvey } from "../../alcoholConsumptionSurvey/base/AlcoholConsumptionSurvey";
import { OutletSurveyFindManyArgs } from "../../outletSurvey/base/OutletSurveyFindManyArgs";
import { OutletSurvey } from "../../outletSurvey/base/OutletSurvey";
import { User } from "../../user/base/User";
import { PoliceStation } from "../../policeStation/base/PoliceStation";
import { SurveyService } from "../survey.service";
@graphql.Resolver(() => Survey)
export class SurveyResolverBase {
  constructor(protected readonly service: SurveyService) {}

  async _surveysMeta(
    @graphql.Args() args: SurveyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Survey])
  async surveys(@graphql.Args() args: SurveyFindManyArgs): Promise<Survey[]> {
    return this.service.surveys(args);
  }

  @graphql.Query(() => Survey, { nullable: true })
  async survey(
    @graphql.Args() args: SurveyFindUniqueArgs
  ): Promise<Survey | null> {
    const result = await this.service.survey(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Survey)
  async createSurvey(@graphql.Args() args: CreateSurveyArgs): Promise<Survey> {
    return await this.service.createSurvey({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,

        policeStation: args.data.policeStation
          ? {
              connect: args.data.policeStation,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Survey)
  async updateSurvey(
    @graphql.Args() args: UpdateSurveyArgs
  ): Promise<Survey | null> {
    try {
      return await this.service.updateSurvey({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,

          policeStation: args.data.policeStation
            ? {
                connect: args.data.policeStation,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Survey)
  async deleteSurvey(
    @graphql.Args() args: DeleteSurveyArgs
  ): Promise<Survey | null> {
    try {
      return await this.service.deleteSurvey(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [AlcoholConsumptionSurvey], {
    name: "alcoholConsumptionSurveys",
  })
  async findAlcoholConsumptionSurveys(
    @graphql.Parent() parent: Survey,
    @graphql.Args() args: AlcoholConsumptionSurveyFindManyArgs
  ): Promise<AlcoholConsumptionSurvey[]> {
    const results = await this.service.findAlcoholConsumptionSurveys(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [OutletSurvey], { name: "outletSurveys" })
  async findOutletSurveys(
    @graphql.Parent() parent: Survey,
    @graphql.Args() args: OutletSurveyFindManyArgs
  ): Promise<OutletSurvey[]> {
    const results = await this.service.findOutletSurveys(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Survey): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => PoliceStation, {
    nullable: true,
    name: "policeStation",
  })
  async getPoliceStation(
    @graphql.Parent() parent: Survey
  ): Promise<PoliceStation | null> {
    const result = await this.service.getPoliceStation(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
