/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { AlcoholConsumptionSurveyListRelationFilter } from "../../alcoholConsumptionSurvey/base/AlcoholConsumptionSurveyListRelationFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { OutletSurveyListRelationFilter } from "../../outletSurvey/base/OutletSurveyListRelationFilter";
import { PoliceStationWhereUniqueInput } from "../../policeStation/base/PoliceStationWhereUniqueInput";

@InputType()
class SurveyWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  completedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  typeField?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => AlcoholConsumptionSurveyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AlcoholConsumptionSurveyListRelationFilter)
  @IsOptional()
  @Field(() => AlcoholConsumptionSurveyListRelationFilter, {
    nullable: true,
  })
  alcoholConsumptionSurveys?: AlcoholConsumptionSurveyListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => OutletSurveyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OutletSurveyListRelationFilter)
  @IsOptional()
  @Field(() => OutletSurveyListRelationFilter, {
    nullable: true,
  })
  outletSurveys?: OutletSurveyListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PoliceStationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PoliceStationWhereUniqueInput)
  @IsOptional()
  @Field(() => PoliceStationWhereUniqueInput, {
    nullable: true,
  })
  policeStation?: PoliceStationWhereUniqueInput;
}

export { SurveyWhereInput as SurveyWhereInput };
