/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { AlcoholConsumptionSurveyCreateNestedManyWithoutSurveysInput } from "./AlcoholConsumptionSurveyCreateNestedManyWithoutSurveysInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { OutletSurveyCreateNestedManyWithoutSurveysInput } from "./OutletSurveyCreateNestedManyWithoutSurveysInput";
import { PoliceStationWhereUniqueInput } from "../../policeStation/base/PoliceStationWhereUniqueInput";

@InputType()
class SurveyCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  completedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeField?: string | null;

  @ApiProperty({
    required: false,
    type: () => AlcoholConsumptionSurveyCreateNestedManyWithoutSurveysInput,
  })
  @ValidateNested()
  @Type(() => AlcoholConsumptionSurveyCreateNestedManyWithoutSurveysInput)
  @IsOptional()
  @Field(() => AlcoholConsumptionSurveyCreateNestedManyWithoutSurveysInput, {
    nullable: true,
  })
  alcoholConsumptionSurveys?: AlcoholConsumptionSurveyCreateNestedManyWithoutSurveysInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => OutletSurveyCreateNestedManyWithoutSurveysInput,
  })
  @ValidateNested()
  @Type(() => OutletSurveyCreateNestedManyWithoutSurveysInput)
  @IsOptional()
  @Field(() => OutletSurveyCreateNestedManyWithoutSurveysInput, {
    nullable: true,
  })
  outletSurveys?: OutletSurveyCreateNestedManyWithoutSurveysInput;

  @ApiProperty({
    required: false,
    type: () => PoliceStationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PoliceStationWhereUniqueInput)
  @IsOptional()
  @Field(() => PoliceStationWhereUniqueInput, {
    nullable: true,
  })
  policeStation?: PoliceStationWhereUniqueInput | null;
}

export { SurveyCreateInput as SurveyCreateInput };
