/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { AlcoholConsumptionSurvey } from "../../alcoholConsumptionSurvey/base/AlcoholConsumptionSurvey";
import { User } from "../../user/base/User";
import { OutletSurvey } from "../../outletSurvey/base/OutletSurvey";
import { PoliceStation } from "../../policeStation/base/PoliceStation";

@ObjectType()
class Survey {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  completedAt!: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeField!: string | null;

  @ApiProperty({
    required: false,
    type: () => [AlcoholConsumptionSurvey],
  })
  @ValidateNested()
  @Type(() => AlcoholConsumptionSurvey)
  @IsOptional()
  alcoholConsumptionSurveys?: Array<AlcoholConsumptionSurvey>;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  user?: User | null;

  @ApiProperty({
    required: false,
    type: () => [OutletSurvey],
  })
  @ValidateNested()
  @Type(() => OutletSurvey)
  @IsOptional()
  outletSurveys?: Array<OutletSurvey>;

  @ApiProperty({
    required: false,
    type: () => PoliceStation,
  })
  @ValidateNested()
  @Type(() => PoliceStation)
  @IsOptional()
  policeStation?: PoliceStation | null;
}

export { Survey as Survey };
