/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SurveyService } from "../survey.service";
import { SurveyCreateInput } from "./SurveyCreateInput";
import { Survey } from "./Survey";
import { SurveyFindManyArgs } from "./SurveyFindManyArgs";
import { SurveyWhereUniqueInput } from "./SurveyWhereUniqueInput";
import { SurveyUpdateInput } from "./SurveyUpdateInput";
import { AlcoholConsumptionSurveyFindManyArgs } from "../../alcoholConsumptionSurvey/base/AlcoholConsumptionSurveyFindManyArgs";
import { AlcoholConsumptionSurvey } from "../../alcoholConsumptionSurvey/base/AlcoholConsumptionSurvey";
import { AlcoholConsumptionSurveyWhereUniqueInput } from "../../alcoholConsumptionSurvey/base/AlcoholConsumptionSurveyWhereUniqueInput";
import { OutletSurveyFindManyArgs } from "../../outletSurvey/base/OutletSurveyFindManyArgs";
import { OutletSurvey } from "../../outletSurvey/base/OutletSurvey";
import { OutletSurveyWhereUniqueInput } from "../../outletSurvey/base/OutletSurveyWhereUniqueInput";

export class SurveyControllerBase {
  constructor(protected readonly service: SurveyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Survey })
  async createSurvey(@common.Body() data: SurveyCreateInput): Promise<Survey> {
    return await this.service.createSurvey({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,

        policeStation: data.policeStation
          ? {
              connect: data.policeStation,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        completedAt: true,
        typeField: true,

        user: {
          select: {
            id: true,
          },
        },

        policeStation: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Survey] })
  @ApiNestedQuery(SurveyFindManyArgs)
  async surveys(@common.Req() request: Request): Promise<Survey[]> {
    const args = plainToClass(SurveyFindManyArgs, request.query);
    return this.service.surveys({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        completedAt: true,
        typeField: true,

        user: {
          select: {
            id: true,
          },
        },

        policeStation: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Survey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async survey(
    @common.Param() params: SurveyWhereUniqueInput
  ): Promise<Survey | null> {
    const result = await this.service.survey({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        completedAt: true,
        typeField: true,

        user: {
          select: {
            id: true,
          },
        },

        policeStation: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Survey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSurvey(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() data: SurveyUpdateInput
  ): Promise<Survey | null> {
    try {
      return await this.service.updateSurvey({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,

          policeStation: data.policeStation
            ? {
                connect: data.policeStation,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          completedAt: true,
          typeField: true,

          user: {
            select: {
              id: true,
            },
          },

          policeStation: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Survey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSurvey(
    @common.Param() params: SurveyWhereUniqueInput
  ): Promise<Survey | null> {
    try {
      return await this.service.deleteSurvey({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          completedAt: true,
          typeField: true,

          user: {
            select: {
              id: true,
            },
          },

          policeStation: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/alcoholConsumptionSurveys")
  @ApiNestedQuery(AlcoholConsumptionSurveyFindManyArgs)
  async findAlcoholConsumptionSurveys(
    @common.Req() request: Request,
    @common.Param() params: SurveyWhereUniqueInput
  ): Promise<AlcoholConsumptionSurvey[]> {
    const query = plainToClass(
      AlcoholConsumptionSurveyFindManyArgs,
      request.query
    );
    const results = await this.service.findAlcoholConsumptionSurveys(
      params.id,
      {
        ...query,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          q1: true,
          q2: true,
          q3: true,
          q4: true,
          q5: true,
          q6: true,
          q7: true,
          q8: true,
          q9: true,
          q10: true,
          q11: true,
          q12: true,
          q13: true,
          q14: true,
          q15: true,
          q16: true,
          q17: true,
          q18: true,
          q19: true,
          q20: true,
          q21: true,
          q22: true,
          q23: true,
          q24: true,
          q25: true,

          survey: {
            select: {
              id: true,
            },
          },
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/alcoholConsumptionSurveys")
  async connectAlcoholConsumptionSurveys(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() body: AlcoholConsumptionSurveyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      alcoholConsumptionSurveys: {
        connect: body,
      },
    };
    await this.service.updateSurvey({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/alcoholConsumptionSurveys")
  async updateAlcoholConsumptionSurveys(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() body: AlcoholConsumptionSurveyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      alcoholConsumptionSurveys: {
        set: body,
      },
    };
    await this.service.updateSurvey({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/alcoholConsumptionSurveys")
  async disconnectAlcoholConsumptionSurveys(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() body: AlcoholConsumptionSurveyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      alcoholConsumptionSurveys: {
        disconnect: body,
      },
    };
    await this.service.updateSurvey({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/outletSurveys")
  @ApiNestedQuery(OutletSurveyFindManyArgs)
  async findOutletSurveys(
    @common.Req() request: Request,
    @common.Param() params: SurveyWhereUniqueInput
  ): Promise<OutletSurvey[]> {
    const query = plainToClass(OutletSurveyFindManyArgs, request.query);
    const results = await this.service.findOutletSurveys(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        q1: true,
        q2: true,
        q3: true,
        q4: true,
        q5: true,
        q6: true,
        q7: true,
        q8: true,
        q9: true,
        q10: true,
        q11: true,
        q12: true,

        survey: {
          select: {
            id: true,
          },
        },

        outlet: {
          select: {
            id: true,
          },
        },

        yesCount: true,
        noCount: true,

        policeStation: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/outletSurveys")
  async connectOutletSurveys(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() body: OutletSurveyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      outletSurveys: {
        connect: body,
      },
    };
    await this.service.updateSurvey({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/outletSurveys")
  async updateOutletSurveys(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() body: OutletSurveyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      outletSurveys: {
        set: body,
      },
    };
    await this.service.updateSurvey({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/outletSurveys")
  async disconnectOutletSurveys(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() body: OutletSurveyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      outletSurveys: {
        disconnect: body,
      },
    };
    await this.service.updateSurvey({
      where: params,
      data,
      select: { id: true },
    });
  }
}
